export { default as clear } from './clear.webp';
export { default as clouds } from './clouds.webp';
export { default as drizzle } from './drizzle.webp';
export { default as rain } from './rain.webp';
export { default as snow } from './snow.webp';
export { default as temp } from './temp.webp';
export { default as thunderstorm } from './thunderstorm.webp';
export { default as moon } from './moon.webp';
export { default as moonClouds } from './moon-clouds.webp';